version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/code
    #command: gunicorn project_name.wsgi:app_name
    command: python manage.py runserver 0.0.0.0:8000