version: '3'
services:
  pdf_reader:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 443:443
      - 80:80
    expose:
      - 8000
    volumes:
      - .:/code
      - ./Nginx/default.conf  :/etc/nginx/conf.d/default.conf
      - ./Nginx/nginx.conf    :/etc/nginx/nginx.conf
      - ./Https/nginx.key :/etc/nginx/certificate/nginx.key
      - ./Https/nginx-certificate.crt :/etc/nginx/certificate/nginx-certificate.crt

    # Keep this order, if changed nginx won't run.
    command:  >
      /bin/bash -c "
             service nginx start &&
             gunicorn PDF_project.wsgi:application --bind 0.0.0.0:8000  --workers 1 --threads 5
             "

              
    
    