version: '3'
services:
  pdf_reader:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - .:/code
    command: gunicorn PDF_project.wsgi:application --bind 0.0.0.0:8000  --workers 1 #--threads 5
  proxy:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Nginx/default.conf  :/etc/nginx/conf.d/default.conf
      - ./Nginx/nginx.conf    :/etc/nginx/nginx.conf
      - ./Https/nginx.key :/etc/nginx/certificate/nginx.key
      - ./Https/nginx-certificate.crt :/etc/nginx/certificate/nginx-certificate.crt